config/routes.rb
Rails.application.routes.draw do
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'sessions#new'
  
  get '/login' => "sessions#new"
  post '/login' => "sessions#create"
  get '/logout' => "sessions#destroy"
  get '/signup' => "users#new"
  post '/signup' => "users#create"
  post '/profile' => "users#complete_update"
  patch '/complete_profile' => "users#complete_profile"
  post '/fundraisers/:fundraiser_id/comments/new' => "comments#create"
  post '/households/:household_id/students/new' => "students#create"
  get '/fundraisers/exceeded_expectations' => "fundraisers#ee"
  get '/fundraisers/most_comments' => "fundraisers#most_comments"

  
  resources :users
  resources :fundraisers do
    resources :reservations, only: [:new, :edit]
    resources :comments, only: [:new, :create, :edit, :update, :destroy]
  end 

  resources :comments, only: :index
  resources :reservations
  resources :schools
  resources :households do 
    resources :students, only: [:new, :create]
  end 
  resources :students
  resources :classrooms, only: [:index, :new, :create]
  

  get '/auth/google_oauth2/callback' => 'sessions#omniauth'

end

app/models/fundraiser.rb
class Fundraiser < ApplicationRecord
    belongs_to :school
    has_many :users
    has_many :comments
    has_many :reservations

    scope :exceeded_expectations?, -> { where('amt_raised > goal')}
    scope :belongs_to_school?, -> (user) { where(school_id: user.school_id)}
    scope :most_comments, -> {self.joins(:comments).group(:id).order("COUNT(comments.id) desc").limit(1)}

    
    
    def completed?
        self.completed == true
    end 

    def status 
        if self.completed == false 
            "Pending"
        else self.completed == true 
            "Completed"
        end 
    end 

    def fundraiser_info(attribute) 
        if self.send(attribute).nil?
            "None specified"
        else 
           self.send(attribute)
        end
    end 

    def format_date
        if self.date.nil?
            "None specified"
        else
            self.date.strftime("%m/%d/%Y")
        end 
    end 

    def percent_of_goal
            x = self.amt_raised - self.goal 
            y = x / self.goal
            z = y * 100 + 100
            z.to_d.truncate(2)
    end 
    
end

app/controllers/fundraisers_controller.rb
class FundraisersController < ApplicationController
    layout "main"

    before_action :school_fundraiser?, only: [:show, :edit, :update, :destroy]
    before_action :is_admin?, only:  [:index, :new, :create, :edit, :update, :destroy, :ee]


    def index
        @fundraisers = Fundraiser.select {|f| f.school == current_user.school}
        respond_to do |format|
            format.html
            format.xlsx
        end
    end 

    def ee 
        @fundraisers = Fundraiser.exceeded_expectations?.belongs_to_school?(current_user)
    end 

    def most_comments 
        @fundraiser = Fundraiser.most_comments.first
    end 

    def new 
        @fundraiser = Fundraiser.new
    end 

    def create
        @fundraiser = Fundraiser.new(fundraiser_params)
        @fundraiser.school = current_user.school
        if @fundraiser.save
            redirect_to user_path(current_user)
        else 
            @fundraiser.errors.full_messages.inspect
            render :new
        end 
    end

    def show 
        @fundraiser = Fundraiser.find(params[:id])
        @household = current_user.household
        @reservation = Reservation.find_by(fundraiser_id: @fundraiser.id, household_id: @household.id)
    end

    def edit 
        @fundraiser = Fundraiser.find(params[:id])
    end 

    def update
        @fundraiser = Fundraiser.find(params[:id])
        if @fundraiser
            @fundraiser.update(fundraiser_params)
            @fundraiser.save
            redirect_to user_path(current_user)
        else 
            @fundraiser.errors.full_messages.inspect 
            render :new 
        end 
    end 

    def destroy 
        @fundraiser = Fundraiser.find(params[:id])
            @fundraiser.reservations.each do |r|
                r.destroy
            end 
            @fundraiser.comments.each do |c|
                c.destroy
            end 
        @fundraiser.destroy

        redirect_to user_path(current_user)

    end 
    
    private 
        def fundraiser_params
            params.require(:fundraiser).permit(:title, :goal, :date, :description, :price, :amt_raised, :time, :duration, :location, :notice, :school_year, :admin_notes, :completed)
        end 
end

app/helpers/fundraisers_helper.rb
module FundraisersHelper

    def school_year 
        [
          '2019-2020',
          '2020-2021',
          '2021-2022',
          '2022-2023',
        ]
    end 

    def require_admin
      current_user.admin == true
    end 

    def completed?(fundraiser)
      if fundraiser.status == "Completed"
        "Completed!"
      end
    end 

    def school_fundraiser?
      @fundraiser = Fundraiser.find(params[:id])
      if @fundraiser.school_id != current_user.school_id
          flash[:alert] = "Must belong to school to continue."
          redirect_to user_path(current_user)
      end 
  end  

  

end

app/views/fundraisers/_edit.html.erb
<% if @fundraiser.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(@fundraiser.errors.count, "error") %> prohibited this account from being created:</h2>

    <ul>
        <% @fundraiser.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
</div>
<% end %>

<%= form_for @fundraiser do |f| %>
    <%= f.label :school_year %>
    <%= f.collection_select :school_year, school_year, :to_str, :to_str, {}, {class: "form-control", :required => true}  %></br>
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control", required: true %></br>
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control", required: true %></br>
    <%= f.label :date %>
    <%= f.date_field :date, class: "form-control", required: true %></br>
    <%= f.label :time %>
    <%= f.time_field :time, class: "form-control", required: true %></br>
    <%= f.label :duration_in_minutes %>
    <%= f.text_field :duration, class: "form-control", required: true %></br>
    <%= f.label :location %>
    <%= f.text_field :location, class: "form-control", required: true %></br>
    <%= f.label :price %>
    <%= f.text_field :price, class: "form-control", required: true %></br>
    <%= f.label :goal %>
    <%= f.text_field :goal, class: "form-control", required: true %></br>
    <%= f.label :notice %>
    <%= f.text_area :notice, class: "form-control" %></br>
    <%= f.check_box :completed, {}, "true", "false" %>
    <%= f.label :completed, class: "checkboxes"%></br>
    <%= f.label :amt_raised %>
    <%= f.text_field :amt_raised, class: "form-control", required: true %></br>
    <%= f.label :admin_notes %>
    <%= f.text_area :admin_notes, class: "form-control" %></br>
    <br>
    
<%= f.submit class: "btn btn-outline-light" %>
<% end %>

app/views/fundraisers/_exceeded_expectations.html.erb
    <%@fundraisers.each do |f|%>
        <h3><%=link_to f.title, fundraiser_path(f)%></h3>
        <br>
    <% end %>

app/views/fundraisers/_form.html.erb
<% if @fundraiser.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(@fundraiser.errors.count, "error") %> prohibited this account from being created:</h2>

    <ul>
        <% @fundraiser.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
</div>
<% end %>

<%= form_for @fundraiser do |f| %>
    <%= f.label :school_year %>
    <%= f.collection_select :school_year, school_year, :to_str, :to_str, {}, {class: "form-control", :required => true}  %></br>
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control", required: true %></br>
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control", required: true %></br>
    <%= f.label :date %>
    <%= f.date_field :date, class: "form-control" %></br>
    <%= f.label :time %>
    <%= f.time_field :time, class: "form-control" %></br>
    <%= f.label :duration_in_minutes %>
    <%= f.text_field :duration, class: "form-control" %></br>
    <%= f.label :location %>
    <%= f.text_field :location, class: "form-control" %></br>
    <%= f.label :price %>
    <%= f.text_field :price, class: "form-control", required: true %></br>
    <%= f.label :goal %>
    <%= f.text_field :goal, class: "form-control", required: true %></br>
    <%= f.label :notice %>
    <%= f.text_area :notice, class: "form-control" %></br>
    
<%= f.submit class: "btn btn-outline-light" %>
<% end %>

app/views/fundraisers/_list.html.erb
<% @fundraisers.each do |f| %>
    <h2 style="color: rgb(0, 141, 184)"><%= link_to f.title, fundraiser_path(f) %></h2>
    <h4>Price per attendee: $<%=f.price%></h4>
    <h4>Status: <%= f.status %></h4>
    <div class="line"></div>
    <h3>Number of Attendees: <%= Reservation.total_attendees(f) %></h3>
    <h3>Students Attending: <%= Reservation.student_attendees(f) %></h3>
        <table class="table table-striped text-center">
            <tr>
                <th><h3>Attendee Name</h3></th>
                <th><h3>Grade</h3></th>
            </tr>
            <% Reservation.attendees_list(f).each do |a| %>
                <tr>
                        <td><%= a.full_name %></td>
                        <td><%= a.grade %></td>
                </tr>
            <% end %>  
        </table>
<% end %>

app/views/fundraisers/edit.html.erb
<div class="clear"></div>

<h1 style="text-align:center">Edit Fundraiser/Event</h1>

<div class="clear"></div>

<div class="form-card">
    <%= render partial: 'edit'%>
</div>

app/views/fundraisers/ee.html.erb
<div class="clear"></div>

    <h1 style="text-align:center">Fundraisers That Exceeded Goal</h1>

    <div class="clear"></div>

    
    <div class="frame-full">
        <%= render partial: 'exceeded_expectations'%>
    </div>

app/views/fundraisers/index.html.erb
    <div class="clear"></div>

    <h1 style="text-align:center">Fundraisers/Events</h1>

    <div class="clear"></div>

    
    <div class="frame-full">
    <%= link_to 'Download as .xlsx', fundraisers_path(format: :xlsx), class: "btn btn-primary push-right", style: "margin-left: 10px;" %>
    <%= link_to "Most Successful Campaigns", fundraisers_exceeded_expectations_path,  class: "btn btn-success push-right"%>
    
        <%= render partial: 'list'%>
    </div>


  

app/views/fundraisers/most_comments.html.erb
<div class="clear"></div>

    <h1 style="text-align:center">Most Commented Fundraiser</h1>

    <div class="clear"></div>

    
    <div class="frame-full">
        <%= @fundraiser.title %>
    </div>

app/views/fundraisers/new.html.erb
<div class="clear"></div>

<h1 style="text-align:center">Add A Fundraiser/Event</h1>

<div class="clear"></div>

<div class="form-card">
    <%= render partial: 'form'%>
</div>

app/views/fundraisers/show.html.erb
<div class="clear"></div>

<div class="frame-full">
    <div class="line"></div>
    
        <h2 style="color: rgb(0, 141, 184)"><%= @fundraiser.title %></h2><h2 style="float:right; color: orange"><%= @fundraiser.status %></h2>
        <p><%= @fundraiser.description %></p>
                
        <table class="table table-striped text-center">
                    <tr>
                        <th><h3>Location</h3></th>
                        <th><h3>Start Time</h3></th>
                        <th><h3>Event Duration</h3></th>
                        <th><h3>Price</h3></th>
                    </tr>
                    <tr>
                        <td><%= @fundraiser.fundraiser_info("location") %></td>
                        <td><%= @fundraiser.time.strftime("%I:%M %p") unless @fundraiser.time.nil?%></td>
                        <td><%= @fundraiser.fundraiser_info("duration") %> minutes</td>
                        <td>$<%= @fundraiser.fundraiser_info("price") %></td>
                    </tr>
        </table>
            <% if @fundraiser.completed? %>
                <h4 style="color:orange">Cannot make any reservations at this time</h4>
            <% elsif !current_user.rsvpd(@fundraiser).empty? && !@fundraiser.completed?%>
                <span style="color: green; float: left">Already RSVP'd!</span>
                <%= link_to "Cancel Reservation", reservation_path(current_user.rsvpd(@fundraiser)), method: :delete, class: "btn btn-danger push-right", style: "margin-left: 10px;"%>
                <%= link_to "Edit Reservation", edit_fundraiser_reservation_path(@fundraiser, current_user.rsvpd(@fundraiser)), class: "btn btn-primary push-right"%>
            <% else !@fundraiser.completed? %>
                <%= link_to 'RSVP!', new_fundraiser_reservation_path(@fundraiser), class: "btn btn-primary", style: "float: right" unless @fundraiser.status == "Completed"%>
            <% end %>

            <div class="clear"></div>
            <div class="line"></div>
            <h1>Comments</h1>
            <div class="line"></div>
            
            <% @fundraiser.comments.reverse.each do |c| %>
                <% if c.user == current_user %>
                    <p><%=link_to c.text, edit_fundraiser_comment_path(@fundraiser, c) %> - <%= c.show_comment_info%>   <%= link_to "Delete", fundraiser_comment_path(@fundraiser, c), method: :delete %></td></p>
                <% else %>
                    <p><%=c.text %> - <%= c.show_comment_info%></p>
                <% end %>
            <% end %>
            
            <div class="line"></div>
            
            <%= render partial: '/comments/comment_field', locals: {fundraiser: @fundraiser} %>

    </div>
   
         <% if current_user.admin? && @fundraiser.completed?%>
            <div class="frame-full">        
                <h3 class="archived"> Admin Notes: <span><%=@fundraiser.admin_notes %></span></h3>
                <h3 class="archived"> Amount Raised: <span>$<%=@fundraiser.amt_raised %></span></h3>
                <h3 class="archived"> Goal: <span>$<%=@fundraiser.goal %> (<%= @fundraiser.percent_of_goal %>% of goal reached)</span></h3>
            </div>
         <% end %> 

 