config/routes.rb
Rails.application.routes.draw do
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'sessions#new'
  
  get '/login' => "sessions#new"
  post '/login' => "sessions#create"
  get '/logout' => "sessions#destroy"
  get '/signup' => "users#new"
  post '/signup' => "users#create"
  post '/profile' => "users#complete_update"
  patch '/complete_profile' => "users#complete_profile"
  post '/fundraisers/:fundraiser_id/comments/new' => "comments#create"
  post '/households/:household_id/students/new' => "students#create"
  get '/fundraisers/exceeded_expectations' => "fundraisers#ee"
  get '/fundraisers/most_comments' => "fundraisers#most_comments"

  
  resources :users
  resources :fundraisers do
    resources :reservations, only: [:new, :edit]
    resources :comments, only: [:new, :create, :edit, :update, :destroy]
  end 

  resources :comments, only: :index
  resources :reservations
  resources :schools
  resources :households do 
    resources :students, only: [:new, :create]
  end 
  resources :students
  resources :classrooms, only: [:index, :new, :create]
  

  get '/auth/google_oauth2/callback' => 'sessions#omniauth'

end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :fundraiser
    belongs_to :user

    
    def post_time
        self.created_at.strftime("%m/%d/%y at %I:%M %p")
    end 

    def show_comment_info
        self.user.first_name + " - " + self.post_time
    end    
    

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    layout "main"

    before_action :my_comment?, only: [:edit, :show, :update,]
    before_action :is_admin?, only: :index

    def index 
        @comments = Comment.select {|c| c.fundraiser.school == current_user.school}
    end 
    
    def new
        @comment = Comment.new
    end 

    def create
        @comment = Comment.new(text: params[:comment], fundraiser_id: params[:fundraiser_id])
        @comment.user_id = current_user.id
        @fundraiser = Fundraiser.find(params[:fundraiser_id])
        if @comment.save
            redirect_to fundraiser_path(@fundraiser)
        end
    end 

    def edit
        @comment = Comment.find(params[:id])
        @fundraiser = @comment.fundraiser
    end 

    def update
        @comment = Comment.find(params[:id])
        if @comment.user == current_user 
            @comment.text = params[:comment]
            @comment.save

            redirect_to fundraiser_path(@comment.fundraiser)
        else 
            flash[:alert] = "Cannot edit another user's comments."
            redirect_to fundraiser_path(@comment.fundraiser)
        end 
    end 

    def destroy
        @fundraiser = Fundraiser.find(params[:fundraiser_id])
        @comment = Comment.find(params[:id])
        if @comment.user == current_user || current_user.admin == true && current_user.school == @fundraiser.school
            @comment.destroy
            redirect_to fundraiser_path(@fundraiser)
        else 
            flash[:alert] = "Unable to delete."
            redirect_to user_path(current_user)
        end
    end 

  
end

app/helpers/comments_helper.rb
module CommentsHelper

    def my_comment?
        @comment = Comment.find(params[:id])
        if @comment.user != current_user 
            flash[:alert] = "Cannot edit a comment that is not yours."
            redirect_to user_path(current_user)
        end 
    end 

        
end

app/views/comments/_comment_field.html.erb
<%= form_tag fundraiser_comments_path(fundraiser) do %>
    <%=text_field_tag :comment, '', size: 100%>
    <%=submit_tag "Post Comment"%>
<% end %>

app/views/comments/_edit_comment.html.erb
<%= form_tag fundraiser_comment_path(fundraiser, comment), :method => :patch do %>
    <%=text_field_tag :comment, '', :value => comment.text, size: 100 %></br>
    </br>
    <%=submit_tag "Edit Comment"%>
<% end %>

app/views/comments/edit.html.erb
<div class="clear"></div>

<div class="form-card">
        <%= render partial: "edit_comment", locals: {fundraiser: @fundraiser, comment: @comment}  %>
</div>

app/views/comments/index.html.erb
<div class="clear"></div>

<div class="frame-full">
        <table class="table table-striped">
            <tr>
                <th><h3>Comment</h3></th>
                <th><h3>User</h3></th>
                <th><h3>Fundraiser</h3></th>
                <th><h3>Time Posted</h3></th>
                <th></th>
            </tr>
            <% @comments.each do |c| %>
            <tr>
                <td><%= c.text %></td>
                <td><%= c.user.full_name %></td>
                <td><%= c.fundraiser.title %></td>
                <td><%= c.post_time %></td>
                <td><%= link_to "Delete", fundraiser_comment_path(c.fundraiser, c), method: :delete %></td>
            </tr>
            <% end %>
        </table>
</div>

app/views/comments/new.html.erb
<div class="clear"></div>

<div class="form-card">
        <%= render partial: "comment_field" %>
</div>