config/routes.rb
Rails.application.routes.draw do
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'sessions#new'
  
  get '/login' => "sessions#new"
  post '/login' => "sessions#create"
  get '/logout' => "sessions#destroy"
  get '/signup' => "users#new"
  post '/signup' => "users#create"
  post '/profile' => "users#complete_update"
  patch '/complete_profile' => "users#complete_profile"
  post '/fundraisers/:fundraiser_id/comments/new' => "comments#create"
  post '/households/:household_id/students/new' => "students#create"
  get '/fundraisers/exceeded_expectations' => "fundraisers#ee"
  get '/fundraisers/most_comments' => "fundraisers#most_comments"

  
  resources :users
  resources :fundraisers do
    resources :reservations, only: [:new, :edit]
    resources :comments, only: [:new, :create, :edit, :update, :destroy]
  end 

  resources :comments, only: :index
  resources :reservations
  resources :schools
  resources :households do 
    resources :students, only: [:new, :create]
  end 
  resources :students
  resources :classrooms, only: [:index, :new, :create]
  

  get '/auth/google_oauth2/callback' => 'sessions#omniauth'

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password 

  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                  format: { with: VALID_EMAIL_REGEX },
                  uniqueness: { case_sensitive: false }
  validates :first_name, length: {minimum: 3}

  belongs_to :school, optional: true
  belongs_to :household, optional: true
  has_many :fundraisers
  has_many :comments, through: :fundraisers
  has_many :students

  accepts_nested_attributes_for :household
  
     
    def full_name 
        self.first_name.capitalize + " " + self.last_name.capitalize
    end 

    def rsvpd(fundraiser)
      self.household.reservations.select do |r|
        r.fundraiser_id == fundraiser.id 
      end 
    end 

    def count_me_in?
      !self.household.reservations.empty?
    end 

    def admin?
      self.admin == true
    end 

    def valid_user?(object)
      logged_in? && object.user_id == session[:user_id]
    end

    def my_reservation(fundraiser)
      self.household.reservations.detect do |r|
        r.fundraiser_id == fundraiser.id
      end
    end 

    def self.from_omniauth(auth)
      where(email: auth.info.email).first_or_initialize do |user|
        user.first_name = auth.info.first_name
        user.last_name = auth.info.last_name
        user.email = auth.info.email
        user.password = SecureRandom.hex
      end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    layout "main"
    

    ADMIN_PIN = "1234"

    def index
    end 

    def new
        @user = User.new
    end 

    def create 
        if @user = User.find_by(email: params[:email]) 
            flash[:message] = "Account found. Please login in."
            redirect_to '/'
        else
            @user = User.new(user_params)
            @user.admin = true if params[:user][:admin_pin] == ADMIN_PIN
            @household = @user.build_household(school_id: params[:user][:school_id])
                if @user.save 
                    log_in(@user)
                    render :show
                else 
                    @user.errors.full_messages.inspect
                    render :new
                end  
            end
    end 

    def complete_profile
        @user = User.find(params[:user][:user_id]) 
        @user.admin = true if params[:user][:admin_pin] == ADMIN_PIN
        @user.school_id = params[:user][:school_id]
        @household = @user.build_household(school_id: params[:user][:school_id])
                if @user.save 
                    log_in(@user)
                    render :show
                else 
                    @user.errors.full_messages.inspect
                    render :new
                end  
     end 

    def show 
        @user = User.find(params[:id])
        @household = @user.household
    end 

    def edit 
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            redirect_to user_path(@user)
        else 
            @user.errors.full_messages.inspect
            render :show
        end
    end 

     

private 

    def user_params
        params.require(:user).permit(:username, :email, :password, :first_name, :last_name, :school_id, :household_id, :admin_pin, :household => [:students_attributes => [:first_name, :last_name, :grade]])
    end 

    def require_login
        unless logged_in?
          redirect_to '/'
        end
    end

end

app/helpers/users_helper.rb
module UsersHelper

    def profile_complete?
        current_user && !current_user.school_id.nil?
    end 

    def valid_user?(object)
        logged_in? && object.user_id == session[:user_id]
    end

    def is_admin?
        if current_user.admin != true  
            flash[:alert] = "Must have admin rights to access."
            redirect_to user_path(current_user) 
        end 
    end 

    def my_student?
        @student = Student.find(params[:id])
        if !current_user.household.students.include?(@student)
          flash[:alert] = "Cannot edit this student."
          redirect_to user_path(current_user)
        end
    end 
  
end

app/views/users/_dash.html.erb
<div class="clear"></div>

<div class="row">
    <div class="col-md-6 col-sm-6">
        <div class="header-frame text-center">
            <h1><%=@user.first_name%>'s School</h1>
        </div>
        <div class="frame">
            <% if @user.admin? && @user.school.classrooms.empty? %>
                <%= link_to 'Initialize Classrooms', new_classroom_path, :class => "btn btn-outline-light btn-sm" %>
            <% end %>
             <%= link_to "View Class Rankings", classrooms_path, :class => "btn btn-success btn-sm", style: "float: right" %></br>
             </br>
                <div class="line"></div>
                <h1>My School</h1>
                <div class="line"></div>
                    <h3><%=@user.school.name%></h3></br>
                    <span>
                        <%=@user.school.address%></br>
                        <%=@user.school.city%>, <%=@user.school.state%> <%=@user.school.zipcode%></br>
                    </span>
                    <%= link_to "Edit Profile", edit_user_path(current_user), :class => "btn btn-primary", :style => "float: right"%>
            </div>
    </div>
    <div class="col-md-6 col-sm-6">
        <div class="header-frame text-center">
            <h1><%=@user.first_name%>'s Household</h1>
        </div>
        <div class="frame text-center">
            <%= link_to "View Household Info", household_path(current_user.household), :class => "btn btn-success btn-sm", style: "float: right" %></br>
            </br>
                <div class="table-responsive">
                    <table class="table table-striped">
                        <tr>
                            <th><h3>Student Name</h3></th>
                            <th><h3>Grade</h3></th>
                            <th><h3>Points</h3></th>
                        </tr>
                            <% @user.household.students.each do |student| %>
                            <tr>
                                <td><%= student.full_name %></td>
                                <td><%= student.grade %></td>
                                <td><%= student.participation_points_by_student %></td>
                            </tr>
                            <% end %>
                    </table>
                        <%= link_to 'Add Student', new_household_student_path(@user.household), :class => "btn btn-primary", :style => "float: left" %>
                </div>
             </div>
    </div>
</div>
    
<div class="clear"></div>

<div class="row">
    <div class="col-md-12 col-sm-12">
        <div class="header-frame-full text-center">
            <h1>Fundraisers/Events</h1>
        </div>
    </div>                     
    <div class="col-md-12 col-sm-12">
            <div class="frame-full text-center">
                <div class="table-responsive">                
                    <table class="table table-striped">
                        <tr>
                            <th></th>
                            <th><h3>Fundraiser/Event</h3></th>
                            <th><h3>Event Date</h3></th>
                            <th><h3>Price</h3></th>
                            <th><h3>Location</h3></th>
                            <th></th>
                        </tr>
                            <% @user.school.fundraisers.each do |fundraiser| %>
                            <% if fundraiser.status == "Completed" %>
                                <tr>
                                    <td>Completed!</td>
                                    <td><%= link_to fundraiser.title, fundraiser_path(fundraiser) %></td>
                                    <td><%= fundraiser.format_date %></td>
                                    <td>$<%= fundraiser.fundraiser_info("price") %></td>
                                    <td><%= fundraiser.fundraiser_info("location") %></td>
                                    <% if @user.admin? %>
                                        <td><%= link_to raw("&#9998;"), edit_fundraiser_path(fundraiser), style: "color: white; margin-right: 5px" %><%= link_to raw("&#10008;"), fundraiser_path(fundraiser), method: :delete %></td>
                                    <% end %>
                                </tr>
                            <% else %>
                            <tr>
                                <% if !current_user.rsvpd(fundraiser).empty? %>
                                    <td><%= link_to "Already RSVP'd! View Details", reservation_path(current_user.my_reservation(fundraiser)), class: "btn btn-link", style: "color: green" %></td>
                                <% else %>
                                    <td><%= link_to "View Details/RSVP!", new_fundraiser_reservation_path(fundraiser), class: "btn btn-link" %></td>
                                <% end %>
                                    <td><%= link_to fundraiser.title, fundraiser_path(fundraiser) %></td>
                                    <td><%= fundraiser.format_date %></td>
                                    <td>$<%= fundraiser.fundraiser_info("price") %></td>
                                    <td><%= fundraiser.fundraiser_info("location") %></td>
                                    <% if @user.admin? %>
                                        <td><%= link_to raw("&#9998;"), edit_fundraiser_path(fundraiser), style: "color: white; margin-right: 5px" %><%= link_to raw("&#10008;"), fundraiser_path(fundraiser), method: :delete %></td>
                                    <% end %>
                                </tr>
                            <% end %>
                        <% end %>
                    </table>
                    <% if @user.admin? %>
                         <%= link_to 'Add Fundraiser', new_fundraiser_path, :class => "btn btn-primary", :style => "float: left" %>
                    <% end %>
                </div>
             </div>
        </div>   
    </div>                         

app/views/users/_edit_form.html.erb
        <% if @user.errors.any? %>
            <div id="error_explanation">
                <h2><%= pluralize(@user.errors.count, "error") %> prohibited this account from being created:</h2>
            
                <ul>
                    <% @user.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                </ul>
            </div>
        <% end %>

<%= form_for @user do |f| %>

    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: "form-control", :required => true %></br>

    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: "form-control", :required => true %></br>

    <h3>Select School</h3>

    <%= f.label :school_name %>
    <%= f.collection_select :school_id, School.all, :id, :name, {}, {class: "form-control", :disabled => "disabled"} %></br>

    <%= f.submit class: "btn btn-outline-light"  %>


<% end %>

app/views/users/_form.html.erb
    <% if @user.errors.any? %>
            <div id="error_explanation">
                <h2><%= pluralize(@user.errors.count, "error") %> prohibited this account from being created:</h2>
            
                <ul>
                    <% @user.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                </ul>
            </div>
        <% end %>

<%= form_for @user do |f| %>
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control", :required => true %></br>

    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control", :required => true %></br>

    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: "form-control", :required => true %></br>

    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: "form-control", :required => true %></br>

    <%= f.label :admin_pin %>
    <%= f.text_field :admin_pin, class: "form-control" %></br>

    <h3>Select School</h3>

    <%= f.label :school_name %>
    <%= f.collection_select :school_id, School.all, :id, :name, {}, {class: "form-control", :required => true} %></br>

    <%= f.submit class: "btn btn-outline-light"  %>


<% end %>

app/views/users/_profile.html.erb
<div class="profile-card-blue">
      <h1><%=link_to "Dashboard", user_path(current_user) %></h1>
  </div>

    <div class="profile-card data-box text-center">
        <h1>Count Me In!</h1>
        <div class="line"></div>
        <% if current_user.count_me_in? %>
            <%= render partial: "users/reservations" %>
        <% end %>
    </div>

    <% if current_user.admin? %>
        <div class="profile-card-green">
            <p><%= link_to "Fundraisers", fundraisers_path, class: "btn btn-outline-light" %></p>
        </div>
        <div class="profile-card-orange">
            <p><%= link_to "Comments", comments_path, class: "btn btn-outline-light" %></p>
        </div>
    <% end %>
  

    <div class="profile-card-red">
        <p><%= link_to "Logout", '/logout', class: "btn btn-outline-light" %></p>
    </div>

app/views/users/_reservations.html.erb
   <% if !current_user.household.reservations.empty? %>
        <% current_user.household.reservations.each do |r| %>
            <h4><%=link_to r.fundraiser.title, fundraiser_path(r.fundraiser) unless r.fundraiser.status == "Completed"%></h4>
        <% end %>
    <% end %>

app/views/users/complete_profile.html.erb
<div class="clear"></div>

<h1 style="text-align:center">Complete Profile</h1>

<div class="clear"></div>

<div class="frame-full">
    <%= form_for @user, :url => { :controller => "users", :action => "complete_profile" } do |f| %>
        <%= f.hidden_field :user_id, :value => @user.id %>
        <%= f.label :admin_pin %>
        <%= f.text_field :admin_pin, class: "form-control" %></br>

        <h3>Select School</h3>

        <%= f.label :school_name %>
        <%= f.collection_select :school_id, School.all, :id, :name, {}, {class: "form-control", :required => true} %></br>

        <%= f.submit "Complete Profile", class: "btn btn-outline-light"  %>

    <% end %>
</div>

    

app/views/users/edit.html.erb
<br>
<h1 style="text-align: center">Update Your Profile...</h1>

<div class="form-card">
    <%= render partial: "edit_form" %>
</div>

app/views/users/new.html.erb
    <div class="clear"></div>

    <h1 style="text-align: center">Create Your Free Account!</h1>
    
    <div class="clear"></div>

    <div class="form-card">
        <%= render partial: "form" %>
    </div>

app/views/users/show.html.erb
<%= render partial: "users/dash" %>