config/routes.rb
Rails.application.routes.draw do
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'sessions#new'
  
  get '/login' => "sessions#new"
  post '/login' => "sessions#create"
  get '/logout' => "sessions#destroy"
  get '/signup' => "users#new"
  post '/signup' => "users#create"
  post '/profile' => "users#complete_update"
  patch '/complete_profile' => "users#complete_profile"
  post '/fundraisers/:fundraiser_id/comments/new' => "comments#create"
  post '/households/:household_id/students/new' => "students#create"
  get '/fundraisers/exceeded_expectations' => "fundraisers#ee"
  get '/fundraisers/most_comments' => "fundraisers#most_comments"

  
  resources :users
  resources :fundraisers do
    resources :reservations, only: [:new, :edit]
    resources :comments, only: [:new, :create, :edit, :update, :destroy]
  end 

  resources :comments, only: :index
  resources :reservations
  resources :schools
  resources :households do 
    resources :students, only: [:new, :create]
  end 
  resources :students
  resources :classrooms, only: [:index, :new, :create]
  

  get '/auth/google_oauth2/callback' => 'sessions#omniauth'

end

app/models/household.rb
class Household < ApplicationRecord
    belongs_to :school
    has_many :users
    has_many :students
    has_many :reservations

    accepts_nested_attributes_for :students, reject_if: :all_blank

  

end

app/controllers/households_controller.rb
class HouseholdsController < ApplicationController
    layout "main"
    
    before_action :my_household?, only: [:edit, :show, :update, :destroy]

    def new
        @household = Household.new
        
    end 

    def create 
        @household = Household.create(school_id: current_user.school_id)
        current_user.household_id = @household.id
        current_user.save
        @student = Student.find_or_create_by(student_params)
        
        redirect_to user_path(current_user)

    end 

    def show 
        @household = Household.find(params[:id])
    end

    private 

        def student_params
            params.require(:household).permit(:student => [:first_name, :last_name, :grade])
        end 

end

app/helpers/households_helper.rb
module HouseholdsHelper
    def my_household?
        @household = Household.find(params[:id])
        if !@household.users.include?(current_user)  
            flash[:alert] = "Cannot view another user's household information."
            redirect_to user_path(current_user)
        end 
    end 
end

app/views/households/_form.html.erb
        <% if @user.errors.any? %>
            <div id="error_explanation">
                <h2><%= pluralize(@user.errors.count, "error") %> prohibited this account from being created:</h2>
            
                <ul>
                    <% @user.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                </ul>
            </div>
        <% end %>

        <%= form_for @household do |f| %>
                <%= f.fields_for @household.build_student do |student| %>
                    <%= student.label :first_name %>
                    <%= student.text_field :first_name, class: "form-control", required: true %></br>
                    <%= student.label :last_name %>
                    <%= student.text_field :last_name, class: "form-control", required: true %></br>
                    <%= student.label :grade %>
                    <%= student.collection_select :grade, grades, :to_s, :to_s, {}, {class: "form-control", :required => true} %></br>
            <% end %>
   
            <%= f.submit "Add Student", class: "btn btn-outline-light"  %>

        <% end %>

app/views/households/new.html.erb
</br>
<h1>Create your Household!</h1>

<div class="form-card">
    <p>Add students to your account.</p>

        <%= render partial: "form" %>

</div>

app/views/households/show.html.erb
<div class="clear"></div>

<div class="row">
        <div class="header-frame text-center">
            <h1>Household Information</h1>
        </div>
</div>

    <div class="row clearfix">
            <div class="frame text-center">
                <table class="table table-striped">
                    <tr>
                        <th> </th>
                        <th><h3>Student Name</h3></th>
                        <th><h3>Grade</h3></th>
                        <th><h3>Participation Points</h3></th>
                        <th><h3>Action</h3></th>
                    </tr>
                        <% @household.students.each do |student| %>
                        <tr>
                            <td class="badges"><%= image_tag(student.badge) %></td>
                            <td><%= student.full_name %></td>
                            <td><%= student.grade %></td>
                            <td><%= student.participation_points_by_student %></td>
                            <td><%= link_to "Edit", edit_student_path(student), :class => "btn btn-primary", style: "margin-right: 10px"%><%= link_to "Delete", student_path(student), :method => "delete", :class => "btn btn-danger"%></td>
                        </tr>
                        <% end %>
       
                </table>
            </div>
        </div>  
        <%= link_to 'Add Student', new_household_student_path(@household), :class => "btn btn-success" %>